### ISSUE TITLE
Is F2 redundant now?

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#140]
F2 (rename) and Room Properties (enter) both have similar if not identical functionality. They go to the room dialog where you can rename the room.

Should we free F2 up for other functionality?

**Comment by JasonLautzenheiser** [comment]
Since F2 is a standard rename keystroke, I'll leave it for now until we come up with a reason to use F2 for something else.  Maybe we can create another issue that would improve the rename functionality...make it more like the region rename.  That would be doable.  But I'll close this one for now and we can open another.
