### ISSUE TITLE
Resize and connection ports on octagonal shape are still square.

### ISSUE THREAD

**Issue by JasonLautzenheiser** [JasonLautzenheiser/trizbort#148]
![image](https://cloud.githubusercontent.com/assets/1239981/9777400/f84f0b60-5731-11e5-9fa8-e1f86745f5a3.png)

**Comment by andrewschultz** [comment]
Oops! I figured I would forget something.

The diagonals should be in the middle of the square, but where should the WWN etc. be? Should they be at the octagon vertices or, say, a bit below?

**Comment by JasonLautzenheiser** [comment]
I think if we just move the corners (NE, SE, NW, SW) in on the lines...the others are fine.

**Comment by andrewschultz** [comment]
Sounds good, though...looking through the code, I think we will want to re-define public Vector GetCorner in Rect.cs, since the corners will be different for ellipses, octagons and rounded rectangles. The second argument looks like it would be better as a RoomShape.

Especially since the Rounded Rectangles could use tweaking, too. I think the ports should move in (rounding * .3) in the X and Y directions.

GetCorner only uses the 2nd argument once in Trizbort's code, from GetPortPosition itself. So I think this is feasible to redefine boolean isEllipse as roomShape thisRoomShape.

I would assume that we can also set the default value to SquareCorners, but I don't know if there are any adverse effects. I am still a C# rookie.

(Also, I added octagonal to the room shapes tab in the room properties dialog. I forgot that.)
