### ISSUE TITLE
1.5.9.2: Copied and Pasted maps are slightly altered

### ISSUE THREAD

**Issue by PlNG** [JasonLautzenheiser/trizbort#156]
Room Objects with colon characters `:` in them get transformed to line break characters `|` and I think Trizbort loses track of colors, assigning White instead of no color.

**Comment by andrewschultz** [comment]
I've seen this bug, too, although I'm unable to reproduce reliably in 1592. Creating a room and using the control-arrow keys 

It did come after I typed in a long room name. It was after I created the big room for my dark-shapes.trizbort file. I hope this narrows things down some--and I'm glad it wasn't just me seeing this.

**Comment by PlNG** [comment]
Here's a copy of the [Hydra Lair Map](https://gist.github.com/PlNG/eb9298b5f5dfaf9c82af#file-hydralair-trizbort) that I've been porting from the Legends of Terris website as a semi-real world example.

**Comment by JasonLautzenheiser** [comment]
Looks like copy / paste is completely broken with one of the latest merges.  I think it has to do with the Octagonal property being added in the copy, but not accounted for in the paste.  This might be unrelated to this original issue, but it needs fixed before we can take care of the other issue.

The copy/paste is an area I've wanted to refactor since I've begun working on the project.  It is too fiddly when adding new elements to the room and trying to add an undo, well...it's next too impossible with the current setup.

**Comment by andrewschultz** [comment]
Yeah, sorry about that. I totally hosed things, but the fix for #162 is okay.

Also, it's cool to see new maps--and I am surprised I never knew about gist.github.com before. So thanks again for your contributions.
