### ISSUE TITLE
Ctrl-Left on connector takes you to incorrect room occassionally.

### ISSUE THREAD

**Issue by JasonLautzenheiser** [JasonLautzenheiser/trizbort#157]
Related to #94 we just merged in.  This appears to happen when we:
* create a room
* Ctrl-Left to create and connect a new room to the left (west)
* Click on connection
* Now Ctrl-Left / Ctrl-Right take you to the wrong rooms.

Probably has to do with the source / target rooms, but haven't looked at code yet.

**Comment by andrewschultz** [comment]
Ouch. Sorry. This is the fault of a typo in a helper function I created to account for different ports.

            if ((dirOne == CompassPoint.WestNorthWest) || (dirOne == CompassPoint.WestSouthWest) || (dirOne == CompassPoint.West))
                if ((dirTwo == CompassPoint.WestNorthWest) || (dirTwo == CompassPoint.WestSouthWest) || (dirTwo == CompassPoint.East))

The problem is, of course, .East should be .West. I did some copy/pasting and I thought I checked. Sorry about that.

I thought there might already be a function that does this but couldn't find one, so if there is, we should replace the code with that, because it's awkward.

Perhaps it would be best to code a new function ApproxDir which maps ENE/E/ESE to E, etc. Maybe it could be reused later.

I think there are also ways to clean up the code in selectRoomRelativeToSelectedConnection so maybe I will send in an update based on that.
