### ISSUE TITLE
Reorganize I7 code by region/room

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#221]
When I wrote the trizbort map for my new game, I got a lot done quickly.

But I think I could've done even more.

The code is currently organized by functionality instead of room, which works, but when I went to modify it for an actual project, there was a lot of back-and-forth.

I made some changes but I'm not sure if they're desirable. I'm also not sure if it'd be better to have an option between detailed formatting and text dumps. So I wanted to enter this issue before dropping a pull request. If you want me to put in an option to export I7 by functionality(old way) or by room/region (new way), I would be glad do the work for that.

I attached what a new export looks like. It is for my IFComp 2012 game. I checked that it compiles in the IDE. Also, this works okay, and there is no difference between the auto.inf code the I7 ide generates, though we may want to switch "X2 is east of X1" to X2 later. But it looks slightly awkward, and I couldn't quite figure how to put "East of X1 is X2" past X2.
[shuf-new-export.txt](https://github.com/JasonLautzenheiser/trizbort/files/65989/shuf-new-export.txt)

X1 is a room. East of X1 is X2.

X2 is a room.

This feels right to me, based on a map I exported to Inform code and the changes I had to make. But I didn't want to just throw the pull request out there. And any improvement suggestions are appreciated.

**Comment by JasonLautzenheiser** [comment]
I'm with you, I've tend to write my I7 code more like your way rather than the old way.  I'm good with switching it...I don't really care if we have an option to go back to the old way or not to be honest.  I'd rather put the work into creating a whole format customization so that we could really let the end-user create their own custom format (maybe even a way to export/share these formats)...plus we could perhaps build it in a way to support whichever language they want to export to......but getting ahead of myself there and that may be a V2 feature.

**Comment by andrewschultz** [comment]
Yeah, it would be great to customize. But I think a template would be awesome. It seems like a lot of work, though. I'd definitely want to see who would use it first.
