### ISSUE TITLE
Issue with object text (with tags) creating invalid I7 source

### ISSUE THREAD

**Issue by JasonLautzenheiser** [JasonLautzenheiser/trizbort#259]
I think we have an issue with the generation of at least I7 source when we start using the object tags.

For example the object text is as follows:

```
Mr Jones[m]
  Hat
    Hatband
  fishbowl
    goldfish
Mrs Jones[f]
  rabbit
```

It generates I7 code of the following:

``` Inform
A Mr Jones is a thing. Mr Jones is a male person in Test Room.
An Hat is a thing in the Mr Jones.
An Hatband is a thing in the Hat.
A fishbowl is a thing in the Mr Jones.
A goldfish is a thing in the fishbowl.
A Mrs Jones is a thing. Mrs Jones is a female person in Test Room.
A rabbit is a thing in the Mrs Jones.
```

This doesn't compile as is.  Problems to start:
- Mr Jones should probably not be defined as a thing first.  It should be sufficient to define him as just a male person.
- the second line probably should be A hat is a thing _worn_ by Mr Jones.  This leads to the question of how to distinguish between something worn and something carried.
- the third line raises the question of how to distinguish if something is in something (is the hatband really in the hat?) or is part of (the hatband is part of the hat)
- Again on line 4 we would need to distinguish between something worn or carried by.  Jones is not a container so the fishbowl should not be "in" mr jones
- same thing could apply to Mrs Jones and the rabbit.

I also fixed a few issues in the last pull request https://github.com/JasonLautzenheiser/trizbort/pull/258 which were just some spacing issues, but it made me notice these other things.

This does open the question that perhaps we need to look deeply at this before we move to much forward with implementing in other languages.  It will take some testing of many different scenarios before we release anything (which I admit I didn't test as well as I should have before I pulled in the commit)....

I was planning on releasing before the end of the year, but this is big enough that I think it needs to wait.  @andrewschultz Let's fully vet this out before  just start coding.  We can use the comments here for discussion (attach files if need be).

**Comment by andrewschultz** [comment]
Good point to all of this. It seemed like it would be good to just have "x is a thing" so it compiles. I can fix the code pretty easily so that it says "x is a (something other than thing)." But we need more than that.

I think I see how to fix the "X is a thing" code and I agree, we need more test files and testing. I didn't consider all these complexities. I went too fast with the new stuff here I think--and while I'd considered some of this, I hadn't nearly considered everything

Immediately, I think we should see:
1) if something has a space after it, define the item above as a container only if it is not defined as a person already.
2) [c] and [w] should also be options for things with spaces in them. C = carried, w = worn. If something has no spaces and is carried/worn, we throw an error.
3) for the hatband example, we need a way to say
X is part of the Y. (X=hatband, Y=hat)
vs
X is a thing in the Y. (Y is a bucket, X is a mop)

These are the big ones but I think there should be more to knock out. While we can't clear everything, and while fixing these may free up smaller ones--yeah, we want to knock out the big ones.

I also think we could add 2 more features, but that means even more testing:
3) (much much more minor) [a] can be an animal for the case of a rabbit.
4) [i] can mean immovable/fixed in place

I will be writing some test files too. In fact, I planned to update testsync.pl so it uses warning and strict (I'm doing that for a lot of my PERL files,) and I will try and add some other files as well specific to this feature. So that'd be a good place to start.

**Comment by andrewschultz** [comment]
So, here's a quick fix, we define a function

```csharp
string primaryI7Description (thing myThing)
{
  if (myThing.isPerson) { return "person"; }
  if (myThing.isSupporter) { return "supporter"; }
  // etc
  return "thing";
}

writer.write("{0} is a {1} in ...", primaryI7Description(myThing));
```

Then we need to make sure it's not duplicated e.g.

```csharp
if (myThing.isPerson && primaryI7Description != "person") { Writer.write("He/she/It is a female/male/neuter person."); } //obviously we want to write in a check for this on top of this code, but right now we want to deal with the primary description.
else
...
Writer.Write ("It is a thing.");
```

This doesn't seem 100% efficient. So I'm open to making it better.

**Comment by JasonLautzenheiser** [comment]
@andrewschultz Sorry about the delay.  

In the above comment, what does #1 do for us....I believe Trizbort already does the supporter / container thing with the spaces **in front of the object**.  So checking for space after it shouldn't do anything.  However, yes don't make it a container / supporter if it's already a person.

The part of we could do perhaps another tag, [a] perhaps for 'attached' since [p] is already used.

I'm sending you an email, here in a moment with some other items

**Comment by JasonLautzenheiser** [comment]
- [ ] A person is defined as a thing first before being defined as a person.
- [ ] Incorrect usage of a/an when the word started with an 'H'
- [ ] If something is a person, then items should be carried or worn.
- [ ] Distinguish between something be contained by or part of something
