### ISSUE TITLE
down/right in custom offset should be up/right?

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#291]
This is probably nitpicking, but using the up arrow on "down" moves the text down, and using it on "up" moves the text up. This seems counterintuitive. Maybe we should have the "down" text say "up" instead?

(Note: I have used the right: a lot more than down: in my initial fixes, and I also use numbers a lot more often, too. So even if this needs a fix it's not critical.)

**Comment by JasonLautzenheiser** [comment]
I may fiddle with the wording...but the reason it is the way it is, because in screen coordinates, positive numbers are down and right.

I thought about making them relative to the direction you've chosen so that it would be down when you selected south but positive would be up when you selected north...but felt that might be too confusing changing the meaning of them. 

I'll think about how to word it better or hide the meaning of the numbers themselves so the users doesn't care if it's positive or negative.
