### ISSUE TITLE
Color issue with Tools->Map settings->Colors and Fonts-> Room Text global parameter.

### ISSUE THREAD

**Issue by chrixxxx** [JasonLautzenheiser/trizbort#310]
I have an issue while trying to change the "default" global color from the menu : Tools -> Map Settings from the tab "Colors and Fonts", item "Room Text".
I can change the color  ..  but changing it it has no effect at all and in the map, all Room Texts  remain of the same color (the light blue they have from start) whatever value I put as color in the global Map Settings.

No problem at all if I change the color for a single room from it's specific Properties menu, it works as it should; but if try to modify the global map setting value through the menu under "Colors and Fonts" tab, the item "Room Text" to change all the rooms text color to a single value (that is what I would like to do) it has no effect at all on the displayed map and absolutely nothing changes.

**Comment by JasonLautzenheiser** [comment]
Thanks for the report....I will take a look into this.

**Comment by JasonLautzenheiser** [comment]
So the issue really stems from the way the colors are handled with regions.  Rooms can have  a region, regions have their own color scheme...rooms without a region have a implicit "no region" which you can define the color of that in the region section.  So currently the Room Text and Fill in the Map Settings -> Colors and Fonts is not used.

I will probably remove them from there is they really serve no use and just add confusion.  I may have rethink how those colors all work, but that would be a bit of an undertaking so as not to break existing maps.

**Comment by chrixxxx** [comment]
Thank you for checking it out.. and for the explanation.
Trizbort was a great software, but you're making it awesome . So much indispensable improvements since you started working on it. I love it, there's nothing like it. It's simple to use and very powerful. Thanks you very much!

**Comment by JasonLautzenheiser** [comment]
Thanks for the encouragement!   It's always good to hear that people like it.  I always appreciate bug reports or feature requests because it lets me know that people are using the software and like it enough to take the time to report or request something.

**Comment by chrixxxx** [comment]
I love Trizbort : ) 
I've been looking for years for a mapping tool that could be easy to use and intuitive but at the same time very versatile and with enough option to make good maps, with no luck at all.
Some months ago I found Trizbort (the original one, which is not updated anymore ) and .. I started using it: it was not perfect for my need,  it lacked many options and it it didn't offer any kind of customization at all (you can't even have room with different colors!)., but it was the closest thing to the ideal software I was looking for.

Some weeks ago, while I  I found your improved version.. and...  YES..   IT'S ABSOLUTELY THE SOFTWARE I WAS DREAMING OF when I started searching : )

It has all I need and it's simple and intuitive to use , exactly I would like it to be  : )

I noticed there are some kind of "tags" in your version of Trizbort that you can use do differentiate the type of objects in the room: I thought it would be nice if these tags, if used, could display the object text in different colours, so you can immediately distinguish.. a scenery object from a container or a character, for example. 
It's not so important, the software is good as it is, but having those tags to "play with" .. made me think about this. ; )

Thank you very much for maintaining this wonderful and awesome piece of software : )

**Comment by JasonLautzenheiser** [comment]
Wow...thanks again for the kind words.  I'm glad you like the software.  I of course give most of the credit to Genstein.   I only added and enhanced some things, but these kind of comments are always appreciated.

I really just tried to add stuff that I found useful myself and there were some basics that were just missing (like individual room colors) that just seemed so natural to put in.   There are still somethings that I think would be a great addition and in fact a necessary one, but because of the current architecture, could be overly difficult to implement.   Hence, I've begun work on a V2 which is a major overhaul and in large part a rewrite.  Very early infancy stages on that one, but hope to get more work in on it as we head into the winter months.

I do intend to continue to update the current version as I can as I don't want to neglect it if there are things that could be added or fixed, so updates to this are forthcoming.  The extension of objects are something I am thinking of as I think it has a lot of potential.

Thanks again for the encouragement!
