### ISSUE TITLE
Can/should trizbort lock a file in use?

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#316]
Maybe we should have a flag to protect a file open in trizbort against outside edits?

I've burned myself opening a file twice in trizbort before. Not often, but it's happened enough to throw this out as a low priority issue.

Test case:

from the command line, 

trizbort myfile.trizbort (twice)

**Comment by JasonLautzenheiser** [comment]
That isn't a bad idea.  Couple questions (somewhat related):

1. Is there a valid use-case for having more than one instance of Trizbort open at a time?   If so, would it be preferred to have separate instances or would a tabbed environment be more useful?

2. Is there a valid reason why you might want the same file open more than once?

3. Should it truly be locked (read-only) so that you can't save the file from say a text editor while it's open in Trizbort?

**Comment by andrewschultz** [comment]
1 I can't think of a critical one. I think the tabbed environment would be more useful. I really like what Notepad++ does with text files. I have text files mapped to it, and if I open one from the command line, Notepad++ opens it in a new tab.

2 I can't think of one, again. If I need to twiddle a file, I just make a backup.

3 probably not, but if it's a choice between locking the file and allowing 2 files, I'd rather have the small nag of having the file locked, just to check off. EG if I edit something in a text editor *and* trizbort before saving, then save in the text editor, I can avoid overwriting that way.

**Comment by JasonLautzenheiser** [comment]
Closing this for now.....Tabbed interface is in the works for V2 and #366 should help with editing files in other applications
