### ISSUE TITLE
Feature Request: Optimize Room Entry Dialog

### ISSUE THREAD

**Issue by ainslec** [JasonLautzenheiser/trizbort#334]
Hello,

Another small feature request. I would like the option to arrange the Room Properties Dialog so that I can quickly enter name, subtitle and description. As such, the description tab seem to me to the best default, but I'm happy if you want to keep existing behaviour and make the change configurable.

My preferred layout and tab stops would be as follows....

![image](https://user-images.githubusercontent.com/201870/27014880-6ceb0152-4ef9-11e7-99dc-6e039beb74a6.png)

What do you think?

**Comment by andrewschultz** [comment]
I think this looks really good. This is something I ran into, but I didn't worry about it much. Since we are able to set start/end rooms other ways, I think they should be pushed to the back. I would suggest the trivial tweak of Dark being 5th in tab order, since it is probably used more than the start/end rooms.

We also might want to dump the square of arrows that place the text in "Objects" last in the tab order.

I'd also like, if we go the route of letting the user choose opening objects or descriptions, to add a third option: open last (e.g. if I opened objects last, it would open objects again, and if descriptions, descriptions. I don't think we need to worry about the default since we can just hit alt-o or alt-e).

This might be a side issue, but maybe a numpad-(1-9) could choose the objects? Let me know if I should report it that way.

**Comment by ainslec** [comment]
Additional keyboard shortcuts are always welcome, and I'm wary of suggesting UI changes that might make things better for myself at the expense of a layout that someone else loves for different reasons. But, I would be over the moon if I could make description the 3rd item in tab order.

And while we are in the realm of wishlists, could we make ctrl+enter be the same as clicking OK?

**Comment by JasonLautzenheiser** [comment]
I am all for making things easier.  To me any additional keyboard shortcuts to allow quick access to any section or shortcut any group of functionality is a bonus.   

I also like the idea of saving the last tab as that gives a sense of context to what the user is currently doing or recently has done)(i.e.  I'm going through all rooms and touching up the description)

I've never been a fan of the whole arrow square box and would welcome a better way to do that...though I'm hesitant to take away the UI without coming up with something that makes more sense.

**Comment by ainslec** [comment]
I don't mean to add pressure, but what kind of timeframe can I expect this to be addressed within? My brother is currently editing an adventure, and it sure would come in handy :)

Also #333 ? That feature would be useful beyond measure.

**Comment by JasonLautzenheiser** [comment]
@andrewschultz Would you want to take a look at these and have time?  I'm right now tied up with other projects for a bit, but can help out if needed.

**Comment by JasonLautzenheiser** [comment]
I just realized that in between invocations of the room dialog, the tab you are on is being saved....so if I switch to the description tab on the first room....the next room I open  will be on the description tab as well.  That doesn't necessarily change the tab order at all, nor does it hold between invocations of Trizbort itself, but it does give you the context that @andrewschultz hinted at in the last tab feature.

**Comment by JasonLautzenheiser** [comment]
Ok....I've adjusted the tab order and layout slightly, code has been committed, will be in the next release
