### ISSUE TITLE
option for in-depth stats?

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#342]
I've been thinking about this for a while. I'm not sure about the best way to go about it.

The basic stats are probably all most people want. But it would be nice to have a list of all sorts of miscellaneous checking stats for advanced users. Stuff like # of up-down passages, in-out, or even bendy passages (e.g. north from one room, west from another).

It would not be too bad to add conditionals to the MainStatisticsView modules for whatever we wanted to measure, but before I start any work, I'm also wondering where we should put the option.

The app settings box is pretty full right now, and besides, I guess a case could be made for putting "Verbose statistics" as an option in the pull-down menu or even using a hotkey for it.

Does anyone have any opinions on

1. if this is a good idea
2. if so, where the option should go?

**Comment by JasonLautzenheiser** [comment]
I don't have it up in front of me at the moment, but I'm not so hung up on if the user sees them all the time or not.  Maybe just show all statistics all the time, we could group them in the output differently perhaps to keep some of the obscure ones together at the bottom, but I don't necessarily want to have more options for the user to choose, because I've found that most people just don't change many options (no data to back that up really, just an observation over my career)

Maybe the stats output page needs to be redesigned to handle more stats in a more friendly way...but that could be a challenge for another day and another issue....for now, I saw add the stats in and lets not worry about adding an option until we absolutely need to.

**Comment by andrewschultz** [comment]
Sounds good. I'll put the speculative stuff near the bottom.

Adding each new stat helps me to learn the sort of things that make C# powerful, so it's good not to have to worry something's too obscure. And maybe the code will help other people who are curious.

So I'll just put a big ====== between important stats and obscure stats for my first push.

**Comment by JasonLautzenheiser** [comment]
Closing this for now as individual issues will be created as needed
