### ISSUE TITLE
Zoom is changing on save

### ISSUE THREAD

**Issue by JasonLautzenheiser** [JasonLautzenheiser/trizbort#346]
if I smartSave, the zoom decreases by 2%. I think we are resizing but not taking some buffer into account when we smartSave.

**Comment by JasonLautzenheiser** [comment]
The problem is in AdjustZoomed in mainform.cs, line 81.

`txtZoom.Value = (int)(Canvas.ZoomFactor*100.00f);`

It looks like a rounding error, as we seem to round down from, say, 82.99999 to 82. Changing 100.00 to 100.01 fixes it, but this seems like an awful hack. I'm not sure if we can do better?

**Comment by JasonLautzenheiser** [comment]
@andrewschultz can you send your sample map?  I can't get this to reproduce.

**Comment by andrewschultz** [comment]
@JasonLautzenheiser the bug shows up more readily when I have the granulated zoom installed in general, because there are more zoom percentages possible. However. I think this is a reliable way to reproduce things. It's document independent.

1. create a small document with a few rooms. It doesn't have to take up the full screen. It's the zoom percentage you specify that's important.
2. zoom out so it's at 80%.
3. zoom out, in, out, in. This will cause it to resize to 63, 78, 62 and 77 %.
4. hit smart-save. 77% drops to 76% if you auto-save in one format, or 75% in two, because Trizbort rounds downward twice (saving as PNG and PDF).

Whether or not Trizbort rounds down depends on the zoom percentage.

**Comment by andrewschultz** [comment]
The rounding error I mentioned is fixable in Canvas.cs (and besides Trizbort stops rounding down after at most 4 mouse wheel up/down movements), but feature creep etc.

ZoomIn:
```ZoomFactor *= 1.25001f;```
(or ZoomFactor *= 1.25f; ZoomFactor += .005 for rounding purposes, since the int() function automatically rounds down)

ZoomOut:
```ZoomFactor /= 1.2499f;```
(or ZoomFactor /= 1.25f; ZoomFactor += .005 for rounding purposes)

Is it worth it?

**Comment by JasonLautzenheiser** [comment]
It's really a pretty harmless issue....probably not worth it, unless we can be assured that the fix suggested actually fixes it and causes no serious side effects.

**Comment by andrewschultz** [comment]
I agree, I'd like to test the changes in Canvas.cs with zoomin/zoomout inaccuracy before submitting it for, say, 1.5.9.10. I'd be willing to do that for the next release.

It's not a big deal, but once I noticed it, it stuck in my mind a bit, enough I'd be willing to test it to have it out of the way..

So, should I send the new zoom merge to fix AdjustZoomed along with the general more precise ctrl-home zooming to fix this issue, , or will we not worry about AdjustZoomed (at least for 1.5.9.9)?

**Comment by JasonLautzenheiser** [comment]
Let's save that for next release.    If you have any more stats changes, go ahead and send those over, otherwise I'll wrap up a few things and prepare for a release in the next day or so.

**Comment by JasonLautzenheiser** [comment]
I've never been able to reproduce this.  Gonna close it
