### ISSUE TITLE
Inconsistent behavior for setting end rooms

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#413]
Create a trizbort file with 2 rooms.

Set room 1 as the end room via the room dialog (highlight it then it return,) then room 2 the same way. Note there is a warning.

Now right click on room 1 and set it as an end room and do likewise for room 2. You're able to set 2 end rooms this way.

Both methods seem plausible, but they're inconsistent. It seems possible we could have 2 different end rooms, so there may be a choice to make--but I think the original feature meant there'd be only one end room, and if we needed more, we could just define an "end" region.

The functions in question are:

* public void SetEndRoom() in CommandController.cs
* private void chkEndRoom_CheckedChanged(object sender, EventArgs e) in RoomProperties

I can take care of this, but I thought I'd check off for what behavior is preferred before doing anything.

**Comment by JasonLautzenheiser** [comment]
This really should be refactored so that both places call the same code....makes sense that it would be done in the SetEndRoom() function.   So the chkEndRoom_checkedchanged function should call into the SetEndRoom I suppose.   

No in regards to whether we can have more than one end room.  I think that is fine.  I really has no impact on any of the code exports, so should be no conflict there having two of them.  

Do we need a warning?  I'm torn on that.  Some may appreciate it, some may be annoyed by it.  I say, lets keep the warning, but allow them to have multiple end rooms.  Eventually, we can add an option at some point to show/not show the warning.

**Comment by JasonLautzenheiser** [comment]
The more I thought about this and started to play with it, I think it's better to just remove the warning and limitation.  End rooms really have no bearing on anything but the map.  So the warning is restrictive.

Now what we could do is add a custom search, validation or stat that will show how many end rooms there are.  I can let that take care of any warning that the user may want.

For now I will remove the warning as it stands now and allow the user to add as many end rooms as they want.
