### ISSUE TITLE
Possible to switch off grid?

### ISSUE THREAD

**Issue by ainslec** [JasonLautzenheiser/trizbort#452]
Hello,

Not sure if this is possible in Trizbort, but went to the view menu to try to switch off the grid likes, and I couldn't find the option.

If the option is there somewhere else, it's worth surfacing the option in the "View" menu, and if it is not an option, can it be an option?

Chris

**Comment by JasonLautzenheiser** [comment]
It is possible.   It is under Tools-> Map Settings and on the Lines and Grids tab.  You can make it visible or not and change some properties.

I suppose it makes since to put that under the View menu for a quick on/off of the grid.

Thanks

![image](https://user-images.githubusercontent.com/1239981/45784484-db66bf80-bc36-11e8-8152-a155c11fb48e.png)

**Comment by Nyun0** [comment]
This is done in my branch [start-end-copy](https://github.com/Nyun0/trizbort/commits/start-end-copy) with commit [9457a40](https://github.com/Nyun0/trizbort/commit/9457a402438f93410a471ed49df93d06612a9888)

**Comment by JasonLautzenheiser** [comment]
Toggle menu item added to the view menu
